# Site settings
title: laobubu的博客
url: "http://blog.laobubu.net"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Chongqing
description: >
  大概就是一个乱七八糟的地方而已。

# Your information
email: laobubu@gmail.com
author: laobubu
avatar: "//cdn.v2ex.com/gravatar/ebcd5f8f5e1cdbbd8b81058d52c252be?s=135"
profile: 一个爱瞎鼓捣的家伙
twitter_username: laobubu
github_username:  laobubu

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: laobubu  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
